image: rocker/tidyverse

stages:
  - build
  - check
  - test

before_script:
  - sudo apt-get install -y libgeos-dev
  - R -e 'install.packages(c("lintr","ggthemes", "sp", "mapproj", "maps", "maptools", "rgeos", "shinycssloaders", "shinydashboard"))'
  - R -e 'devtools::install_github("USGS-R/wateRuse")'

buildsource:
  stage: build
  script:
    - R CMD build . --no-build-vignettes --no-manual

checkerrors:
  stage: check
  script:
    - R -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["errors"]], character(0))) stop("Check with Errors")'

checkwarnings:
  stage: check
  script:
    - R -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["warnings"]], character(0))) stop("Check with Warnings")'

checknotes:
  stage: check
  script:
    - R -e 'if (!identical(devtools::check(document = FALSE, args = "--no-tests")[["notes"]], character(0))) stop("Check with Notes")'

unittests:
  stage: test
  script:
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'

codecov:
  stage: test
  script:
    - R -e 'covr::codecov()'

style:
  stage: test
  script:
    - R -e 'lintr::lint_package()'
