image: rocker/tidyverse

stages:
  - build
  - check
  - test

before_script:


buildsource:
  stage: build
  script:
    - sudo apt-get install -y libgeos-dev
    - R -e 'install.packages(c("lintr","ggthemes", "sp", "mapproj", "maps", "maptools", "rgeos", "shinycssloaders", "shinydashboard"))'
    - R -e 'devtools::install_github("USGS-R/wateRuse")'
    - R CMD build . --no-build-vignettes --no-manual

checkerrors:
  stage: check
  script:
    - R -e 'devtools::check(document = FALSE, args = "--no-tests")'

unittests:
  stage: test
  script:
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'

codecov:
  stage: test
  script:
    - R -e 'covr::codecov()'

style:
  stage: test
  script:
    - R -e 'lintr::lint_package()'
