image: rocker/tidyverse

stages:
  - check
  - test

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  CODECOV_TOKEN: "CODECOV_TOKEN_STRING"
  APT_PKGS: "libgeos-dev"
  CRAN_MIRROR: "https://cloud.r-project.org"
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  CHECK_DIR: "$CI_PROJECT_DIR/ci/logs"


getready:
  stage: .pre
  script:
    - mkdir -p $R_LIBS_USER $BUILD_LOGS_DIR
    - apt-get update
    - apt-get -o dir::cache::archives="apt-cache" install -y --no-install-recommends ${APT_PKGS}
    - R -e 'install.packages(c("lintr","ggthemes", "sp", "mapproj", "maps", "maptools", "rgeos", "shinycssloaders", "shinydashboard"), repos = Sys.getenv("CRAN_MIRROR"), lib = Sys.getenv("R_LIBS_USER"))'
    - R -e 'withr::with_libpaths(new = Sys.getenv("R_LIBS_USER"), remotes::install_github("USGS-R/wateRuse",  repos = Sys.getenv("CRAN_MIRROR")))'
  cache:
    paths:
     - $R_LIBS_USER
     - apt-cache/
  artifacts:
    paths:
     - $R_LIBS_USER
     - apt-cache/

buildcheck:
  stage: check
  script:
    - apt-get -o dir::cache::archives="apt-cache" install -y --no-install-recommends ${APT_PKGS}
    - apt-get -o dir::cache::archives="apt-cache" install -y --no-install-recommends qpdf pandoc pandoc-citeproc
    - R CMD build . --no-build-vignettes --no-manual
    - R -e '.libPaths()'
    - R -e 'devtools::check(document = FALSE, args = "--no-tests", error_on = "error")'
    - R -e 'lintr::lint_package()'
    

unittests:
  stage: test
  script:
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'

covertests:
  stage: test
  script:
    - R -e 'x <- covr::package_coverage();x'
    - R -e 'write.table(percent_coverage(x), file = "test.txt", row.names = FALSE, col.names = FALSE)'


    
