image: rocker/tidyverse

stages:
  - check

variables:
  _R_CHECK_CRAN_INCOMING_: "false"
  _R_CHECK_FORCE_SUGGESTS_: "true"
  CODECOV_TOKEN: "CODECOV_TOKEN_STRING"
  APT_PKGS: "libgeos-dev"
  CRAN_MIRROR: "https://cloud.r-project.org"

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends ${APT_PKGS}
  - apt-get install -y --no-install-recommends qpdf pandoc pandoc-citeproc
  - R -e 'install.packages(c("lintr","ggthemes", "sp", "mapproj", "maps", "maptools", "rgeos", "shinycssloaders", "shinydashboard"), repos = Sys.getenv("CRAN_MIRROR"))'
  - R -e 'devtools::install_github("USGS-R/wateRuse",  repos = Sys.getenv("CRAN_MIRROR"))'

buildcheck:
  stage: check
  script:
    - R CMD build . --no-build-vignettes --no-manual
    - R -e 'devtools::check(document = FALSE, args = "--no-tests", error_on = "error")'
    - R -e 'if (any(as.data.frame(devtools::test())[["failed"]] > 0)) stop("Some tests failed.")'
    - R -e 'covr::package_coverage()'
    - R -e 'lintr::lint_package()'

    
